import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WalletContextProvider } from "@/context/Wallet";
import { Toaster } from "react-hot-toast";

const roboto = localFont({
  src: "./fonts/RobotoMonoVariable.ttf",
  variable: "--font-roboto-mono-variable",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Amplify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased min-h-screen bg-gradient-to-br from-blue-400 to-purple-500 text-white`}
      >
        <Toaster />
        <WalletContextProvider>{children}</WalletContextProvider>
      </body>
    </html>
  );
}
