import type { Metadata } from "next";
import localFont from "next/font/local";
import {Roboto_Mono} from "next/font/google"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const roboto = Roboto_Mono({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Get Your Lawyer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/logo.svg" type="image/x-icon" />
        <link rel="apple-touch-icon" href="/logo.svg" />
      </head>
      <body
        className={roboto.className}
      >
        {children}
      </body>
    </html>
  );
}
